apiVersion: v1
kind: Pod
metadata:
  name: pod-annotation
  annotations:
    builder: "nimkoes (nimkoes@gmail.com)"
    buildDate: "20211226"
    imageRegistry: https://hub.docker.com/
spec:
  containers:
  - name: nginx
    image: nginx:1.14
    ports:
    - containerPort: 80
